### ISSUE TITLE
TopoGNN MUTAG error

### ISSUE THREAD

**Issue by soham0209** [BorgwardtLab/TOGL#10]
Hi,
When running TopoGNN with `poetry run python topognn/train_model.py --model TopoGNN --dataset MUTAG --max_epochs 10`, the run fails with: `/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.`
I am almost sure that this is not an environment issue since other datasets such as DD, IMDB-MULTI runs successfully.
My guess is that the labels for MUTAG is incorrect.

**Comment by Pseudomanifold** [comment]
I can't reproduce this error—does it still occur? We are using the`TUDatasets` version of `MUTAG` and are not updating labels ourselves.

**Comment by soham0209** [comment]
Thank you, Bastien for replying. I am guessing that the version of pyg is different for me since I had to change pyg version to make it suitable for my environment.
