### ISSUE TITLE
TopologyLayer import error

### ISSUE THREAD

**Issue by okin1234** [BorgwardtLab/TOGL#11]
Hi there,
Thank you for providing the codebase.
I am currently testing without using Poetry to understand how the topology layer works.
However, the following error occurs when importing the "torch_persistent_homology" used to import the "TopologyLayer".
Is there a way to solve the error below or a calculation file of Python version instead of C++ in "torch_person_homology"?
![image](https://user-images.githubusercontent.com/73921285/197538129-bdd2970d-626c-4c57-966d-6ce74a24d4bb.png)

**Comment by Pseudomanifold** [comment]
Hi! This is a great idea—we could provide a Python-based implementation but currently lack the resources to implement this.
