### ISSUE TITLE
unable to detect torch module

### ISSUE THREAD

**Issue by FaizanHassanSiddiqui** [BorgwardtLab/TOGL#14]
Hi,

I am trying to run the code on google colab. I have installed all the packages listed in .lock file using poetry but when I try to run the train_model.py, it throws an error that there is no module named torch? What am I missing here? Any idea?

**Comment by Pseudomanifold** [comment]
Hi,

This is not an error specifically arising from TOGL, so I suggest you check whether `torch` has been installed correctly. Feel free to reopen the issue if the error persists.
