### ISSUE TITLE
Missing submodule repos

### ISSUE THREAD

**Issue by adrianlzt** [BorgwardtLab/TOGL#2]
Hi!
I was trying to use this repo but it has a git submodule pointing to a no longer existing repo: https://github.com/ExpectationMax/torch_persistent_homology/tree/eea88014ba6acd72f5003680afd7a26b4057ce23

Could be possible to restore that third repo or to include it here?
Maybe @ExpectationMax?

Thanks!

**Comment by Pseudomanifold** [comment]
Thanks for pointing this out! I think the repo is still private; we'll make it public ASAP.

**Comment by ExpectationMax** [comment]
Sorry for the delay! The repo is now public :) Feel free to reopen the issue in case something still isn't working.
