### ISSUE TITLE
Failed to run  ‘poetry install’

### ISSUE THREAD

**Issue by lizhou21** [BorgwardtLab/TOGL#5]
After poetry is installed, there exits "  ValueError" when I run "poetry install".
It prompts that "  Directory .\TOGL-main\repos\pyper does not seem to be a Python package"?
How can I solve this problem?

**Comment by Pseudomanifold** [comment]
This looks like you might be missing submodules. Please try executing the following commands:

```console
git submodule init
git submodule update
```

**Comment by lizhou21** [comment]
I have loaded the submodule before. But it is strange that yes still prompts: " Directory .\TOGL-main\repos\pyper does not seem to be a Python package"? 

- repos 
    - pyper 
        - persistent_homology 
        - representations 
        - __init__.py 
        - statistics.py 
        - utilities.py 
        - vectorisation.py 
    - torch_persistent_homology 
        -  __init__.py 
        - perisistent_homology_cpu.cpp 
        - unionfind.hh

**Comment by Pseudomanifold** [comment]
Thanks for the clarification! Which poetry version are you using?

**Comment by lizhou21** [comment]
Oh! I solved it. 
In fact, I failed to use "git submodule update", in which it prompts "fatal: Could not read from remote repository. …… ".
So I directly git each submodule separately.
But I mistakenly moved in only the contents of the subfolder "pyper".

Thanks so much for the reply.

**Comment by Pseudomanifold** [comment]
Great, happy to hear that the problem got resolved!
