### ISSUE TITLE
Implementing Topo Graph based learning for Point clouds

### ISSUE THREAD

**Issue by prashkmr** [BorgwardtLab/TOGL#8]
Hi Bastian,

I went through your video at Oxford Summer School and landed here after watching the talk on topo GNN. This is impressive.

I was thinking of whether this work can be applied to LiDAR point clouds where node relations between adjacent nodes have to be discovered.
Given this work is applied on graphs where edge information is available unlike LiDAR point clouds where we the edges and their strength has to be discovered. Would this work there or what modification would I need to make in order to get this code running for point clouds.

Eagerly awaiting your reply.

Thanks,
Prashant

**Comment by Pseudomanifold** [comment]
Dear Prashant,

> I went through your video at Oxford Summer School and landed here after watching the talk on topo GNN. This is impressive.

Thanks! All the credit belongs to my ingenious co-authors!

> I was thinking of whether this work can be applied to LiDAR point clouds where node relations between adjacent nodes have to be discovered. Given this work is applied on graphs where edge information is available unlike LiDAR point clouds where we the edges and their strength has to be discovered. Would this work there or what modification would I need to make in order to get this code running for point clouds.

I think this is possible; if you are interested in characterising such a point cloud as a "mesh" of potentially unknown connectivity, TOGL is probably not the best fit---that being said, other topological machine learning methods that are not necessarily based on graphs might be more appropriate here. Check out [`pytorch-topological`](https://github.com/aidos-lab/pytorch-topological), for instance.

Let's take this discussion to an e-mail conversation! Looking forward to chatting with you!
